### ISSUE TITLE
metrics in go-libp2p

### ISSUE THREAD

**Issue by p-shahi** [libp2p/blog#69]
go-lipp2p has added metrics https://github.com/libp2p/go-libp2p/issues/1356 across many components for better observability and debug-ability

Users have already found this effort useful. In order to widely announce this feature and showcase how to observe metrics (with examples), we should have an accompanying blog post.

**Comment by sukunrt** [comment]
I'll give it a try

**Comment by BigLep** [comment]
I'm reopening because:
1. I made some adjustments in https://github.com/libp2p/blog/pull/105
2. I think we should provide more context arouund the "public dashboards": https://github.com/libp2p/go-libp2p/blob/master/dashboards/README.md#public-dashboards

About the dashboards:
1. It's great we have these - thanks!
2. In https://github.com/libp2p/go-libp2p/blob/master/dashboards/README.md#public-dashboards, lets add more context about these.  Maybe something along the lines of:

```
These metrics come from one of the public IPFS DHT [bootstrap nodes](https://docs.ipfs.tech/concepts/nodes/#bootstrap) run by Protocol Labs.  At least of 202308, these nodes handle many connections across various libp2p implementations, versions, and. configurations.  They don't handle large file transfers.   
```

Concerning the dashboards themselves (e.g., https://protocollabs.grafana.net/public-dashboards/fce8fdeb629742c89bd70f0ce38dfd97?orgId=1 )

<img width="1401" alt="image" src="https://github.com/libp2p/blog/assets/85411/95eb462c-cc73-4d84-8ee5-12c0b755ba53">

I'm missing context when I load it.  A couple of things:
1. Change to "go-libp2p Autonat" rather than "libp2p autonat"?
2. Can we add a text panel that points back https://github.com/libp2p/go-libp2p/blob/master/dashboards/README.md#public-dashboards ?  Basically something like `See https://github.com/libp2p/go-libp2p/blob/master/dashboards/README.md#public-dashboards for more context.`

**Comment by sukunrt** [comment]
Thanks @BigLep for the suggestions. This context will be helpful for users. 

Does this look good? 
https://protocollabs.grafana.net/public-dashboards/fce8fdeb629742c89bd70f0ce38dfd97?orgId=1

**Comment by p-shahi** [comment]
It lgtm, @BigLep I'm going to close this, please re-open if something is amiss
